import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { css } from "@pigment-css/react";
import "./globals.css";
import "@pigment-css/react/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DARK = "@media (prefers-color-scheme: dark)";

const htmlClass = css(({ theme }) => ({
  backgroundColor: theme.colorSchemes.light.colors.background,
  color: theme.colorSchemes.light.colors.foreground,
  [DARK]: {
    backgroundColor: theme.colorSchemes.dark.colors.background,
    color: theme.colorSchemes.dark.colors.foreground,
  },
}));

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${htmlClass}`}
      >
        {children}
      </body>
    </html>
  );
}
